# Generated by Django 5.2.13 on 2026-05-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
